name: check_instance
on:
  workflow_dispatch:
concurrency: only_one_run_at_a_time
jobs:
  check_your_permission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v3
      - name: check your permission
        run: |
          if grep -Fxq "$GITHUB_ACTOR" ./.github/workflows/start_process_allow_list
          then
              echo "INFO::Passed"
          else
              echo "ERROR::Please make a pull request to add your github username in '.github/workflows/start_process_allow_list'"
              exit 1
          fi
  call_context_check:
    needs: check_your_permission
    uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
  check_if_instance_running:
    needs: call_context_check
    runs-on: ubuntu-latest
    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
     - name: Check instance
       id: check_instance
       run: |
         export STATE=$(aws ec2 describe-instances --output text --filters Name=instance-id,Values=${{ secrets.INSTANCE_ID }} --query "Reservations[].Instances[].State[].Name[]")
         echo "instance_state=$STATE" >> $GITHUB_OUTPUT
     - name: Trigger process
       if: ${{ steps.check_instance.outputs.instance_state }} == "stopped"
       uses: ${{ github.repository }}/.github/workflows/start_process.yaml@main
     - name: Instance is still running
       if: ${{ steps.check_instance.outputs.instance_state }} == "running"
       run: |
         echo "INFO:: instance state is running"
       
         
         
         
