name: force_stop_process
on:
  workflow_dispatch:
jobs:
  call_context_check:
    uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
  force_stop_process:
    needs: call_context_check
    runs-on: ubuntu-latest
    env:
      INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
      INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: force stop worker instance
        run: |
          echo "INFO::start worker instance"
          aws ec2 stop-instances --instance-ids ${INSTANCE_ID}
