name: start_process
on:
    workflow_dispatch:
jobs:
    check_your_permission:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout workflow repo
              uses: actions/checkout@v3
            - name: check your permission
              run: |
                  if grep -Fxq "$GITHUB_ACTOR" ./.github/workflows/start_process_allow_list
                  then
                      echo "INFO::Passed"
                  else
                      echo "ERROR::Please make a pull request to add your github username in '.github/workflows/start_process_allow_list'"
                      exit 1
                  fi
    call_context_check:
        needs: check_your_permission
        uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
    start_process:
        needs: call_context_check
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: start worker instance
              env:
                  INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
              run: |
                  echo "INFO::start worker instance"
                  aws ec2 start-instances --instance-ids ${INSTANCE_ID}
            - name: start process
              run: |
                  echo "INFO::start process"
