name: start_process
on:
    workflow_dispatch:
jobs:
    check_your_permission:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout workflow repo
              uses: actions/checkout@v3
            - name: check your permission
              run: |
                  if grep -Fxq "$GITHUB_ACTOR" ./.github/workflows/start_process_allow_list
                  then
                      echo "INFO::Passed"
                  else
                      echo "ERROR::Please make a pull request to add your github username in '.github/workflows/start_process_allow_list'"
                      exit 1
                  fi
            # - name: passed
            #   if: contains('["yambottle","ttngu207"]', github.actor)
            #   run: echo "INFO::Passed"
            # - name: you don't have permission
            #   if: contains('["yambottle","ttngu207"]', github.actor)==false
            #   run: |
            #       echo "ERROR::Please your repo owner or admin to add your github username to the action secrets"
            #       exit 1
    call_context_check:
        needs: check_your_permission
        uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
    start_process:
        needs: call_context_check
        runs-on: ubuntu-latest
        steps:
            - name: start worker instance
              run: |
                  echo "INFO::start worker instance"
            - name: start process
              run: |
                  echo "INFO::start process"
